spring.application.name=SpringSecExpl

# ==========================================================
# DATABASE
# ==========================================================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/telusko}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:azerty}

spring.jpa.hibernate.ddl-auto=update


# ==========================================================
# SPRING SECURITY
# ==========================================================

spring.security.user.name=${APP_USERNAME:ruqaia}
spring.security.user.password=${APP_PASSWORD:azerty}