spring.application.name=SpringSecExpl


spring.datasource.url=jdbc:postgresql://localhost:5432/telusko
spring.datasource.username=postgres
spring.datasource.password=azerty
spring.jpa.hibernate.ddl-auto=update


spring.security.user.name=ruqaia
spring.security.user.password=azerty